permalink: /:year-:month-:day-:title 

title : Xavierskip
tagline: computer;internet;sport;music;personal


name : xavier skip
description: xavier skip's blog
url: http://blog.xavierskip.com

production_url : http://blog.xavierskip.com

markdown: kramdown
paginate: 16
pygments: true
# auto: true



# defaults:
#   -
#     scope:
#         path: ""
#     values:
#         layout: "t"
#         author: "Mr. skip"
#         def: "defaults test"

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
# analytics :
#   provider : google
#   google : 
#   tracking_id : 'UA-56943415-1'
#   getclicky :
#   site_id : 